### ISSUE TITLE
Misplaced comma on mobile

### ISSUE THREAD

**Issue by tb7512** [jacksonwelsh/govote#5]
![SmartSelect_20220318-155059_Chrome](https://user-images.githubusercontent.com/44574525/159081976-5a93b2ac-abf8-4c08-b84c-4cea2fce0a12.jpg)
Floating comma between Leif's @ and the and

**Comment by ObieMunoz** [comment]
@tb7512 @jacksonwelsh The solution you merged was an exact copy of my suggestion. Although this was a very simple fix, this is a public project. If you're not open to others resolving issues when you _publicly make them_, I suggest making this repository private instead of simply stealing credit.

**Comment by jacksonwelsh** [comment]
@ObieMunoz this is a course project that is required to be public for grader visibility; we are not permitted to accept commits from other users.

**Comment by ObieMunoz** [comment]
> @ObieMunoz this is a course project that is required to be public for grader visibility; we are not permitted to accept commits from other users.

No problem... If, in the future, you could note that somewhere either in issues themselves or in your README.md, that kind of situation could be easily avoided. Good luck to you all!
